### ISSUE TITLE
Empty response from Sinatra app run with rackup when Gemfile.lock is not present

### ISSUE THREAD

**Issue by thitch97** [paketo-buildpacks/rackup#77] opened 2020-09-29 20:08 UTC
Using [this example app](https://github.com/paketo-buildpacks/rackup/tree/87009e907f06152e6fad59b61da64e42280b75a6/integration/testdata/sinatra_app), if the Gemfile.lock is removed and no specific version of the `rack` gem is added to the Gemfile, the following response is returned from the running application:
 
```
$ curl http://localhost:8080
curl: (52) Empty reply from server
```

We expect that either a `Gemfile.lock` or a simple `gem 'rack'` directive in the `Gemfile` would result in a working application. Instead, users would have to specify the `rack` gem with a specific version, as below, to obtain a working application image:
```
 source 'https://rubygems.org' 
                                                                                                                                              
 gem 'sinatra'
 gem 'rack', '~>1.5.1' 
```

**Comment by fg-j** [comment] 2021-11-30 22:48
@paketo-buildpacks/ruby-maintainers This issue has been open for a while. Has this bug been reproduced? Are there blockers in resolving it?

**Comment by sophiewigmore** [comment] 2021-12-03 18:50
I just tried to reproduce this issue with https://github.com/paketo-buildpacks/rackup/tree/87009e907f06152e6fad59b61da64e42280b75a6/integration/testdata/sinatra_app, removed `Gemfile.lock`, and added `gem 'rack'` to the `Gemfile`.
I was able to build (Paketo Rackup Buildpack v0.0.59), run, and curl the app successfully, and receive "Hello world!" back.

@thitch97 I am going to close out this issue since I cannot reproduce it. Please feel free to reopen if this is still an issue you are observing.

**Closed by sophiewigmore** 2021-12-03 18:50 UTC
